import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product.js';
import connectDB from '../config/db.js';

dotenv.config();

const products = [
  {
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
    category: "electronics",
    brand: "SoundMax",
    countInStock: 50,
    rating: 4.5,
    numReviews: 120,
    featured: true,
  },
  {
    name: "Smart Watch Pro",
    description: "Advanced smartwatch with fitness tracking, heart rate monitor, GPS, and 7-day battery life. Water resistant up to 50m.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
    category: "electronics",
    brand: "TechWear",
    countInStock: 30,
    rating: 4.8,
    numReviews: 85,
    featured: true,
  },
  {
    name: "Men's Classic Leather Jacket",
    description: "Premium genuine leather jacket with quilted lining. Classic design perfect for any occasion. Available in black and brown.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
    category: "men's clothing",
    brand: "LeatherCraft",
    countInStock: 25,
    rating: 4.6,
    numReviews: 65,
    featured: true,
  },
  {
    name: "Women's Elegant Summer Dress",
    description: "Beautiful flowy summer dress made from premium cotton. Perfect for parties, weddings, and special occasions.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500",
    category: "women's clothing",
    brand: "FashionStyle",
    countInStock: 40,
    rating: 4.7,
    numReviews: 95,
    featured: true,
  },
  {
    name: "Gold Plated Necklace",
    description: "Elegant 18K gold plated necklace with diamond cut pendant. Perfect gift for special occasions.",
    price: 159.99,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500",
    category: "jewelery",
    brand: "LuxuryGold",
    countInStock: 20,
    rating: 4.9,
    numReviews: 45,
    featured: true,
  },
  {
    name: "Laptop Stand Aluminum",
    description: "Ergonomic aluminum laptop stand with adjustable height. Improves posture and desk organization.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500",
    category: "electronics",
    brand: "DeskPro",
    countInStock: 60,
    rating: 4.4,
    numReviews: 78,
    featured: false,
  },
  {
    name: "Men's Casual T-Shirt Pack",
    description: "Pack of 3 high-quality cotton t-shirts. Comfortable fit, breathable fabric, perfect for everyday wear.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "men's clothing",
    brand: "ComfortWear",
    countInStock: 100,
    rating: 4.3,
    numReviews: 150,
    featured: false,
  },
  {
    name: "Women's High Heels",
    description: "Stylish high heel shoes with comfortable padding. Perfect for office and evening events. Available in multiple colors.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500",
    category: "women's clothing",
    brand: "StepUp",
    countInStock: 35,
    rating: 4.5,
    numReviews: 68,
    featured: false,
  },
  {
    name: "Silver Bracelet Set",
    description: "Beautiful set of 3 sterling silver bracelets. Stackable design, perfect for layering. Comes in elegant gift box.",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500",
    category: "jewelery",
    brand: "SilverCraft",
    countInStock: 30,
    rating: 4.6,
    numReviews: 52,
    featured: false,
  },
  {
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with precision tracking. Long battery life, silent clicks, perfect for work and gaming.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=500",
    category: "electronics",
    brand: "ClickPro",
    countInStock: 80,
    rating: 4.4,
    numReviews: 112,
    featured: false,
  },
  {
    name: "Men's Denim Jeans",
    description: "Classic fit denim jeans made from premium cotton. Comfortable and durable, perfect for everyday wear.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
    category: "men's clothing",
    brand: "DenimCo",
    countInStock: 55,
    rating: 4.5,
    numReviews: 89,
    featured: false,
  },
  {
    name: "Women's Handbag",
    description: "Elegant leather handbag with multiple compartments. Spacious design perfect for daily use. Available in black and brown.",
    price: 119.99,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=500",
    category: "women's clothing",
    brand: "BagLux",
    countInStock: 28,
    rating: 4.7,
    numReviews: 73,
    featured: false,
  },
  {
    name: "Wireless Earbuds Pro",
    description: "Premium wireless earbuds with active noise cancellation, 8-hour battery life, and crystal clear sound quality.",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500",
    category: "electronics",
    brand: "AudioTech",
    countInStock: 75,
    rating: 4.6,
    numReviews: 210,
    featured: true,
  },
  {
    name: "Men's Business Suit",
    description: "Classic tailored business suit perfect for formal occasions. Premium fabric with modern fit. Available in navy, black, and gray.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500",
    category: "men's clothing",
    brand: "FormalWear",
    countInStock: 15,
    rating: 4.8,
    numReviews: 45,
    featured: true,
  },
  {
    name: "Women's Winter Coat",
    description: "Warm and stylish winter coat with faux fur lining. Water-resistant outer layer perfect for cold weather.",
    price: 189.99,
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500",
    category: "women's clothing",
    brand: "WinterStyle",
    countInStock: 32,
    rating: 4.7,
    numReviews: 88,
    featured: false,
  },
  {
    name: "Diamond Engagement Ring",
    description: "Stunning diamond engagement ring in classic solitaire setting. 1 carat center stone with 18K gold band.",
    price: 2999.99,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500",
    category: "jewelery",
    brand: "DiamondLux",
    countInStock: 8,
    rating: 5.0,
    numReviews: 32,
    featured: true,
  },
  {
    name: "Gaming Keyboard RGB",
    description: "Mechanical gaming keyboard with RGB backlighting, customizable keys, and ultra-responsive switches.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=500",
    category: "electronics",
    brand: "GameGear",
    countInStock: 45,
    rating: 4.5,
    numReviews: 156,
    featured: false,
  },
  {
    name: "Men's Running Shoes",
    description: "Lightweight running shoes with advanced cushioning technology. Perfect for marathon runners and daily joggers.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
    category: "men's clothing",
    brand: "RunMax",
    countInStock: 60,
    rating: 4.6,
    numReviews: 234,
    featured: false,
  },
  {
    name: "Women's Sunglasses Designer",
    description: "Luxury designer sunglasses with UV protection and polarized lenses. Fashion-forward frames for all face shapes.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500",
    category: "women's clothing",
    brand: "SunStyle",
    countInStock: 40,
    rating: 4.8,
    numReviews: 92,
    featured: false,
  },
  {
    name: "Gold Chain Necklace",
    description: "Classic gold chain necklace with adjustable length. 18K gold plated, perfect for layering or wearing alone.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1603561596112-0a132f4c6f18?w=500",
    category: "jewelery",
    brand: "GoldCraft",
    countInStock: 50,
    rating: 4.5,
    numReviews: 127,
    featured: false,
  },
  {
    name: "Tablet 10-inch",
    description: "10-inch high-resolution tablet perfect for work, entertainment, and creativity. Long battery life and fast performance.",
    price: 349.99,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500",
    category: "electronics",
    brand: "TabPro",
    countInStock: 25,
    rating: 4.7,
    numReviews: 98,
    featured: true,
  },
  {
    name: "Men's Polo Shirt",
    description: "Classic polo shirt made from premium cotton. Comfortable fit perfect for casual and semi-formal occasions.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    category: "men's clothing",
    brand: "ClassicWear",
    countInStock: 80,
    rating: 4.4,
    numReviews: 189,
    featured: false,
  },
  {
    name: "Women's Sportswear Set",
    description: "Matching sports bra and leggings set. Breathable, moisture-wicking fabric perfect for yoga, gym, and running.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500",
    category: "women's clothing",
    brand: "ActiveWear",
    countInStock: 55,
    rating: 4.6,
    numReviews: 145,
    featured: false,
  },
  {
    name: "Pearl Earrings",
    description: "Elegant pearl drop earrings with sterling silver hooks. Timeless classic perfect for any occasion.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=500",
    category: "jewelery",
    brand: "PearlLux",
    countInStock: 35,
    rating: 4.7,
    numReviews: 78,
    featured: false,
  },
  {
    name: "Portable Bluetooth Speaker",
    description: "Waterproof portable speaker with 360-degree sound. Perfect for outdoor adventures and pool parties.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
    category: "electronics",
    brand: "SoundWave",
    countInStock: 90,
    rating: 4.5,
    numReviews: 201,
    featured: false,
  },
  {
    name: "Men's Hoodie",
    description: "Comfortable pullover hoodie with soft fleece lining. Perfect for casual wear and chilly days.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500",
    category: "men's clothing",
    brand: "CozyWear",
    countInStock: 70,
    rating: 4.4,
    numReviews: 167,
    featured: false,
  },
  {
    name: "Women's Maxi Dress",
    description: "Elegant maxi dress with flowing silhouette. Perfect for summer parties, weddings, and special events.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1566479179817-5dc5c44d2c79?w=500",
    category: "women's clothing",
    brand: "Elegance",
    countInStock: 42,
    rating: 4.8,
    numReviews: 112,
    featured: true,
  },
  {
    name: "Rose Gold Watch",
    description: "Stylish rose gold watch with leather strap. Elegant design perfect for both casual and formal wear.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
    category: "jewelery",
    brand: "TimeLux",
    countInStock: 20,
    rating: 4.9,
    numReviews: 56,
    featured: true,
  },
  {
    name: "4K Monitor 27-inch",
    description: "Ultra HD 4K monitor with HDR support. Perfect for gaming, design work, and video editing.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
    category: "electronics",
    brand: "DisplayPro",
    countInStock: 18,
    rating: 4.7,
    numReviews: 67,
    featured: false,
  },
  {
    name: "Men's Winter Jacket",
    description: "Warm and durable winter jacket with down insulation. Waterproof outer shell perfect for extreme cold.",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
    category: "men's clothing",
    brand: "WinterGear",
    countInStock: 30,
    rating: 4.6,
    numReviews: 95,
    featured: false,
  },
  {
    name: "Women's Ankle Boots",
    description: "Stylish ankle boots with block heel for comfort. Perfect for autumn and winter seasons.",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500",
    category: "women's clothing",
    brand: "BootStyle",
    countInStock: 38,
    rating: 4.5,
    numReviews: 124,
    featured: false,
  },
  {
    name: "Silver Pendant Necklace",
    description: "Beautiful silver pendant necklace with intricate design. Comes with adjustable chain length.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500",
    category: "jewelery",
    brand: "SilverDesign",
    countInStock: 45,
    rating: 4.6,
    numReviews: 103,
    featured: false,
  },
  {
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1583863788434-e58c31d565c0?w=500",
    category: "electronics",
    brand: "ChargeTech",
    countInStock: 100,
    rating: 4.4,
    numReviews: 178,
    featured: false,
  },
  {
    name: "Men's Dress Shirt",
    description: "Premium dress shirt with wrinkle-resistant fabric. Perfect for business meetings and formal events.",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500",
    category: "men's clothing",
    brand: "FormalShirt",
    countInStock: 65,
    rating: 4.5,
    numReviews: 143,
    featured: false,
  },
  {
    name: "Women's Tote Bag",
    description: "Spacious tote bag made from durable canvas. Perfect for work, shopping, and everyday use.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=500",
    category: "women's clothing",
    brand: "BagEssentials",
    countInStock: 52,
    rating: 4.4,
    numReviews: 119,
    featured: false,
  },
  {
    name: "Titanium Ring Set",
    description: "Modern titanium wedding ring set with brushed finish. Lightweight, durable, and hypoallergenic.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500",
    category: "jewelery",
    brand: "ModernRings",
    countInStock: 15,
    rating: 4.8,
    numReviews: 41,
    featured: false,
  },
  {
    name: "USB-C Hub Adapter",
    description: "Multi-port USB-C hub with HDMI, USB 3.0, and SD card slots. Perfect for laptops and tablets.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=500",
    category: "electronics",
    brand: "ConnectPro",
    countInStock: 85,
    rating: 4.3,
    numReviews: 162,
    featured: false,
  },
  {
    name: "Men's Shorts",
    description: "Comfortable cargo shorts with multiple pockets. Perfect for summer and casual outings.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500",
    category: "men's clothing",
    brand: "SummerWear",
    countInStock: 75,
    rating: 4.3,
    numReviews: 98,
    featured: false,
  },
  {
    name: "Women's Scarf Set",
    description: "Luxurious silk scarf set with vibrant patterns. Perfect accessory for any outfit.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500",
    category: "women's clothing",
    brand: "StyleAccess",
    countInStock: 60,
    rating: 4.5,
    numReviews: 87,
    featured: false,
  },

  {
    name: "test",
    description: "Luxurious silk scarf set with vibrant patterns. Perfect accessory for any outfit.",
    price: 100,
    image: "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500",
    category: "women's clothing",
    brand: "StyleAccess",
    countInStock: 2,
    rating: 4.5,
    numReviews: 87,
    featured: false,
  },
];

const seedProducts = async () => {
  try {
    await connectDB();
    await Product.deleteMany({});
    console.log('✅ Existing products deleted');
    const createdProducts = await Product.insertMany(products);
    console.log(`✅ ${createdProducts.length} products inserted successfully!`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();

